language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install -r requirements_test.txt
  - python setup.py develop

script:
  - make test

after_success:
  - coveralls

notifications:
  email: false
